apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: host-app
  template:
    metadata:
      labels:
        app: host-app
    spec:
      containers:
        - name: host-app
          image: "{{ .Values.image.repository }}/host-app:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
