apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microfrontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mfe.arrivia.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: host-app
                port:
                  number: 80
          - path: /search
            pathType: Prefix
            backend:
              service:
                name: product-search
                port:
                  number: 80
          - path: /filter
            pathType: Prefix
            backend:
              service:
                name: product-filter
                port:
                  number: 80                  
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: product-details
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
