apiVersion: v1
kind: Service
metadata:
  name: product-filter-mfe
spec:
  type: {{ .Values.service.type }}
  selector:
    app: product-filter-mfe
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
